package main

import (
	"encoding/json"
	"fmt"
	"os"
	"net/http"
)

type AutoGenerated struct {
	Success bool `json:"success"`
	Data    []struct {
		ID         string        `json:"id"`
		Idx        int           `json:"idx"`
		Name       string        `json:"name"`
		URL        string        `json:"url"`
		Tags       []interface{} `json:"tags"`
		Sign       string        `json:"sign"`
		Feed       string        `json:"feed"`
		Status     string        `json:"status"`
		Repeat     bool          `json:"repeat"`
		Enabled    bool          `json:"enabled"`
		Sitemap    string        `json:"sitemap"`
		Arch       string        `json:"arch"`
		JoinTime   int64         `json:"join_time"`
		UpdateTime int64         `json:"update_time"`
		SavewebID  string        `json:"saveweb_id"`
		Recommend  bool          `json:"recommend"`
	} `json:"data"`
}

func main() {
	log.Print("getting blogs...")
	response, err := http.Get("https://zhblogs.ohyee.cc/api/blogs/random")
	if err != nil {
		log.Fatal(err)
	}
	log.Print(response)

	var websites AutoGenerated
	json.Unmarshal(response, &websites)
	log.Print(websites.data[1].url)

	for i := 0; i < len(websites.data); i++ {
		api = "https://zh-blogs.icodeq.com/page_archive?url="
		http.Get(api+websites.data[i].url)
}