name: AutoArchive
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  builds:
    name: AutoArchive
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Golang Runtime
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Run
        run: go run archive.go
